# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: AutoCompilation

on:
  workflow_dispatch:
  push:
    paths:
      - 'source/**'
      - '.github/workflows/AutoCompilation.yml'
      
jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai
          pip install pycryptodome
          pip install pyinstaller
          pip install requests
          pip install markdown
          pip install pillow
          pip install pyqt6
      
      - name: Init Files(Code)
        run: |
          mkdir temp1\SourceCode\source
          mkdir temp1\SourceCode\images
          copy source\* temp1\SourceCode\source
          copy images\* temp1\SourceCode\images

      - name: Upload SourceCode
        uses: actions/upload-artifact@v4
        with:
          name: SourceCode
          path: temp1\SourceCode

      - name: Create Executable
        run: |
          cd source
          pyinstaller --onefile --windowed --icon '..\images\Gemini.ico' Gemini.py Blurlabel.py Checkupdate.py Decrypt.py Historywindow.py Main.py MainWindow.py MoveLabel.py Msgbox.py Rwconfig.py SettingWindow.py CustomFrame.py
          cd ..

      - name: Init Files(Gemini)
        run: |
          mkdir temp2\GeminiAI
          mkdir temp2\GeminiAI\images
          copy source\dist\Gemini.exe temp2\GeminiAI\Gemini.exe
          copy images\* temp2\GeminiAI\images
          copy config.json temp2\GeminiAI\config.json

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Gemini-Artifacts
          path: temp2