# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: 自动编译exe

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai
          pip install pyinstaller
          pip install pyqt6

      - name: Create Executable
        run: |
          pyinstaller --onefile --windowed --icon 'images\Gemini.ico' Gemini.py

      - name: Move Executable
        run: |
          move dist\Gemini.exe Gemini.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Gemini-Artifacts
          path: |
            images/
            config.json
            Gemini.exe